Make ECS async aware
AgnostiqHQ/covalent-ecs-plugin pull request #42
Opened 2022-10-11 19:51 UTC by FyzHsn

- [ ] I have added the tests to cover my changes.
- [ ] I have updated the documentation and CHANGELOG accordingly.
- [ ] I have read the CONTRIBUTING document.

2022-10-12 20:41 UTC, AlejandroEsquivel commented
Hey @FyzHsn, I do think it might make sense to reduce some of the repetition by the introduction of something like:
```python
def _execute_partial_in_threadpool(partial_func):
  loop = asyncio.get_running_loop()
  future = await loop.run_in_executor(None, partial_object)
  return future
```

then can be used as such:

```python
run_task_response = _execute_partial_in_threadpool(partial(
            ecs.run_task,
            taskDefinition=self.ecs_task_family_name,
            launchType="FARGATE",
            cluster=self.ecs_cluster_name,
            count=1,
            networkConfiguration={
                "awsvpcConfiguration": {
                    "subnets": [self.ecs_task_subnet_id],
                    "securityGroups": [self.ecs_task_security_group_id],
                    # This is only needed if we're using public subnets
                    "assignPublicIp": "ENABLED",
                },
            },
))
     
```

This will also decouple which executor is used to execute the partials from all of the individual functions.

2022-10-12 20:44 UTC, FyzHsn commented
> Hey @FyzHsn, I do think it might make sense to reduce some of the repetition by the introduction of something like:
> 
> ```python
> def _execute_partial_in_threadpool(partial_func):
>   loop = asyncio.get_running_loop()
>   future = await loop.run_in_executor(None, partial_object)
>   return future
> ```
> 
> then can be used as such:
> 
> ```python
> run_task_response = _execute_partial_in_threadpool(partial(
>             ecs.run_task,
>             taskDefinition=self.ecs_task_family_name,
>             launchType="FARGATE",
>             cluster=self.ecs_cluster_name,
>             count=1,
>             networkConfiguration={
>                 "awsvpcConfiguration": {
>                     "subnets": [self.ecs_task_subnet_id],
>                     "securityGroups": [self.ecs_task_security_group_id],
>                     # This is only needed if we're using public subnets
>                     "assignPublicIp": "ENABLED",
>                 },
>             },
> ))
>      
> ```
> 
> This will also decouple which executor is used to execute the partials from all of the individual functions.

Sweet! That's an awesome suggestion. Making the change now

2022-10-14 19:48 UTC, AlejandroEsquivel requested changes
Looks great @FyzHsn , just some very minor changes

2022-10-14 19:48 UTC, AlejandroEsquivel commented on covalent_ecs_plugin/ecs.py
> +        loop = asyncio.get_running_loop()
should use `_execute_partial_in_threadpool` for consistency

2022-10-14 19:48 UTC, AlejandroEsquivel commented on covalent_ecs_plugin/ecs.py
> +        return await loop.run_in_executor(None, self.query_result, task_metadata)
same here

2022-10-14 20:00 UTC, AlejandroEsquivel approved these changes

2022-10-14 20:05 UTC, merged